# Generated by Django 3.2.3 on 2021-06-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alarmdisabled_prediction_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm_logs',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
