# Generated by Django 3.2.3 on 2021-06-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_alarm_logs_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_device', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('en_L1', models.FloatField()),
                ('cons_en_L1', models.FloatField()),
                ('en_L2', models.FloatField()),
                ('cons_en_L2', models.FloatField()),
                ('en_L3', models.FloatField()),
                ('cons_en_L3', models.FloatField()),
                ('cons_glbal', models.FloatField()),
            ],
        ),
    ]
